/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyChartLine: typeof import('@opentiny/vue')['ChartLine']
    TinyChartPie: typeof import('@opentiny/vue')['ChartPie']
    TinyCol: typeof import('@opentiny/vue')['Col']
    TinyImage: typeof import('@opentiny/vue')['Image']
    TinyLayout: typeof import('@opentiny/vue')['Layout']
    TinyRadar: typeof import('@opentiny/vue')['Radar']
    TinyRow: typeof import('@opentiny/vue')['Row']
    TinyStatistic: typeof import('@opentiny/vue')['Statistic']
  }
}
